DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'nautilus_projection_writer') THEN
        REVOKE INSERT, UPDATE ON execution_events FROM nautilus_projection_writer;
        REVOKE INSERT, UPDATE ON orders_projection FROM nautilus_projection_writer;
        REVOKE INSERT, UPDATE ON positions_projection FROM nautilus_projection_writer;
        REVOKE INSERT, UPDATE ON accounts_projection FROM nautilus_projection_writer;
        REVOKE USAGE ON TYPE position_side_v1, reconciliation_state_v1 FROM nautilus_projection_writer;
        REVOKE USAGE ON SCHEMA public FROM nautilus_projection_writer;
    END IF;
END $$;

DROP INDEX IF EXISTS idx_replay_results_raw_message_id;
DROP INDEX IF EXISTS idx_replay_results_replay_run_id;
DROP INDEX IF EXISTS idx_replay_runs_status;
DROP INDEX IF EXISTS idx_outbox_events_created_at;
DROP INDEX IF EXISTS idx_outbox_events_aggregate;
DROP INDEX IF EXISTS idx_outbox_events_status;
DROP INDEX IF EXISTS idx_audit_events_created_at;
DROP INDEX IF EXISTS idx_audit_events_trace_id;
DROP INDEX IF EXISTS idx_audit_events_aggregate;
DROP INDEX IF EXISTS idx_node_heartbeats_last_seen_at;
DROP INDEX IF EXISTS idx_risk_state_account_id;
DROP INDEX IF EXISTS idx_accounts_projection_reconciliation_state;
DROP INDEX IF EXISTS idx_accounts_projection_account_id;
DROP INDEX IF EXISTS idx_positions_projection_instrument_id;
DROP INDEX IF EXISTS idx_positions_projection_account_id;
DROP INDEX IF EXISTS idx_orders_projection_venue_order_id;
DROP INDEX IF EXISTS idx_orders_projection_intent_id;
DROP INDEX IF EXISTS idx_orders_projection_account_id;
DROP INDEX IF EXISTS idx_execution_events_ts_event;
DROP INDEX IF EXISTS idx_execution_events_intent_id;
DROP INDEX IF EXISTS idx_execution_events_account_id;
DROP INDEX IF EXISTS idx_execution_commands_status;
DROP INDEX IF EXISTS idx_execution_commands_intent_id;
DROP INDEX IF EXISTS idx_trade_intents_status;
DROP INDEX IF EXISTS idx_trade_intents_account_id;
DROP INDEX IF EXISTS idx_trade_intents_risk_decision_id;
DROP INDEX IF EXISTS idx_trade_intents_hermes_decision_id;
DROP INDEX IF EXISTS idx_risk_decisions_status;
DROP INDEX IF EXISTS idx_risk_decisions_account_id;
DROP INDEX IF EXISTS idx_risk_decisions_hermes_decision_id;
DROP INDEX IF EXISTS idx_hermes_decisions_message_action;
DROP INDEX IF EXISTS idx_hermes_decisions_context_snapshot_id;
DROP INDEX IF EXISTS idx_hermes_decisions_processing_run_id;
DROP INDEX IF EXISTS idx_hermes_decisions_raw_message_id;
DROP INDEX IF EXISTS idx_context_snapshots_raw_message_id;
DROP INDEX IF EXISTS idx_message_processing_runs_status;
DROP INDEX IF EXISTS idx_message_processing_runs_raw_message_id;
DROP INDEX IF EXISTS idx_media_assets_sha256;
DROP INDEX IF EXISTS idx_media_assets_raw_message_id;
DROP INDEX IF EXISTS idx_raw_messages_content_hash;
DROP INDEX IF EXISTS idx_raw_messages_channel_received;

DROP TABLE IF EXISTS replay_results;
DROP TABLE IF EXISTS replay_runs;
DROP TABLE IF EXISTS outbox_events;
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS node_heartbeats;
DROP TABLE IF EXISTS risk_state;
DROP TABLE IF EXISTS accounts_projection;
DROP TABLE IF EXISTS positions_projection;
DROP TABLE IF EXISTS orders_projection;
DROP TABLE IF EXISTS execution_events;
DROP TABLE IF EXISTS execution_commands;
DROP TABLE IF EXISTS trade_intents;
DROP TABLE IF EXISTS risk_decisions;
DROP TABLE IF EXISTS hermes_decisions;
DROP TABLE IF EXISTS context_snapshots;
DROP TABLE IF EXISTS message_processing_runs;
DROP TABLE IF EXISTS media_assets;
DROP TRIGGER IF EXISTS trg_raw_messages_source_received_at_insert_only ON raw_messages;
DROP TABLE IF EXISTS raw_messages;
DROP FUNCTION IF EXISTS prevent_raw_messages_source_received_at_update();

DROP ROLE IF EXISTS nautilus_projection_writer;

DROP TYPE IF EXISTS replay_status;
DROP TYPE IF EXISTS execution_command_status;
DROP TYPE IF EXISTS risk_decision_status;
DROP TYPE IF EXISTS trade_intent_status;
DROP TYPE IF EXISTS outbox_status;
DROP TYPE IF EXISTS reconciliation_state_v1;
DROP TYPE IF EXISTS entry_type_v1;
DROP TYPE IF EXISTS position_side_v1;
DROP TYPE IF EXISTS account_scope_v1;
DROP TYPE IF EXISTS approved_trade_action_v1;
DROP TYPE IF EXISTS hermes_action_v1;
DROP TYPE IF EXISTS message_type_v1;
