from pathlib import Path


CONTRACTS_VERSION = "contracts-v1"

CONTRACTS_ROOT = Path(__file__).resolve().parent
VERSION_MANIFEST_PATH = CONTRACTS_ROOT / "version.json"
V1_ROOT = CONTRACTS_ROOT / "v1"

HERMES_DECISION_V1_SCHEMA_PATH = V1_ROOT / "hermes_decision.v1.json"
APPROVED_TRADE_INTENT_V1_SCHEMA_PATH = V1_ROOT / "approved_trade_intent.v1.json"
EXECUTION_EVENT_ENVELOPE_V1_SCHEMA_PATH = V1_ROOT / "execution_event_envelope.v1.json"
SYSTEM_SNAPSHOT_V1_SCHEMA_PATH = V1_ROOT / "system_snapshot.v1.json"

SCHEMA_PATHS = {
    "HermesDecisionV1": HERMES_DECISION_V1_SCHEMA_PATH,
    "ApprovedTradeIntentV1": APPROVED_TRADE_INTENT_V1_SCHEMA_PATH,
    "ExecutionEventEnvelopeV1": EXECUTION_EVENT_ENVELOPE_V1_SCHEMA_PATH,
    "SystemSnapshotV1": SYSTEM_SNAPSHOT_V1_SCHEMA_PATH
}

__all__ = [
    "CONTRACTS_VERSION",
    "CONTRACTS_ROOT",
    "VERSION_MANIFEST_PATH",
    "V1_ROOT",
    "HERMES_DECISION_V1_SCHEMA_PATH",
    "APPROVED_TRADE_INTENT_V1_SCHEMA_PATH",
    "EXECUTION_EVENT_ENVELOPE_V1_SCHEMA_PATH",
    "SYSTEM_SNAPSHOT_V1_SCHEMA_PATH",
    "SCHEMA_PATHS"
]

