#!/usr/bin/env python3
"""Patch the pinned HK legacy control-plane with dynamic account multipliers.

The default invocation targets the production checkout:

    python3 scripts/patch_legacy_control_plane_multiplier.py

Use ``--check`` to validate readiness without writing. The patch only accepts
the reviewed production preimage and the exact output generated by this file.
"""

from __future__ import annotations

import argparse
import errno
import hashlib
import json
import os
import stat
import tempfile
from pathlib import Path

EXPECTED_SOURCE_SHA256 = (
    "953a429f3290e64409784e1fc9ce5e69f1fbff2eb94646ff313fdae7769ee943"
)
EXPECTED_PATCHED_SHA256 = (
    "8130d5dbe2d52d81c95fa988463c4d4cc1e1f6d8a3776a762dbdff62f535ecbe"
)
PATCH_MARKER = "# legacy-control-plane-multiplier-patch:v1"
DEFAULT_TARGET = Path(
    "/srv/trader-v3/services/control-plane/api/read_api.py"
)


class PatchError(RuntimeError):
    """Raised when the target cannot be patched with the reviewed transform."""


_OLD_ACCOUNTS = '_OPERATOR_ACCOUNTS = ("account-a", "account-b")'
_NEW_ACCOUNTS = """\
# legacy-control-plane-multiplier-patch:v1
_OPERATOR_ACCOUNTS = (
    "account-a",
    "account-b",
    "account-c",
    "account-d",
)"""

_ROUTING_INSERT_ANCHOR = """\
_ATTRIBUTION_SHADOW_LOG = "/srv/trader-v3/logs/attribution-shadow.jsonl"


def _channel_from_signal_ref(value) -> str | bool:
"""

_ROUTING_INSERT_REPLACEMENT = """\
_ATTRIBUTION_SHADOW_LOG = "/srv/trader-v3/logs/attribution-shadow.jsonl"


def _watcher_account_is_enabled(row, account_columns: set[str]) -> bool:
    for field_name in ("is_enabled", "enabled"):
        if field_name not in account_columns:
            continue
        value = str(row[field_name] or "").strip().lower()
        if value not in {"1", "active", "enabled", "true"}:
            return False
    if "status" not in account_columns:
        return True
    status = str(row["status"] or "").strip().lower()
    return not status or status in {"1", "active", "enabled", "true"}


def _watcher_risk_capital_multiplier(
    account_id: str,
    channel_id: str | bool = False,
) -> float:
    import sqlite3

    normalized_account_id = str(account_id or "").strip()
    if normalized_account_id not in _OPERATOR_ACCOUNTS:
        raise HTTPException(
            status_code=503,
            detail="watcher execution account identity is invalid",
        )
    normalized_channel_id = str(channel_id or "").strip()
    try:
        conn = sqlite3.connect(
            f"file:{_WATCHER_TRADING_DB}?mode=ro",
            uri=True,
        )
        conn.row_factory = sqlite3.Row
        try:
            account_columns = {
                str(row["name"])
                for row in conn.execute(
                    "PRAGMA table_info(account_configs)"
                ).fetchall()
            }
            required_account_columns = {
                "account_id",
                "execution_account_id",
                "risk_capital_multiplier",
            }
            if not required_account_columns <= account_columns:
                raise HTTPException(
                    status_code=503,
                    detail="watcher account risk schema is unavailable",
                )
            fields = [
                "account.account_id AS account_id",
                "account.execution_account_id AS execution_account_id",
                "account.risk_capital_multiplier "
                "AS risk_capital_multiplier",
            ]
            for field_name in ("is_enabled", "enabled", "status"):
                if field_name in account_columns:
                    fields.append(f"account.{field_name} AS {field_name}")
            if normalized_channel_id:
                route_columns = {
                    str(row["name"])
                    for row in conn.execute(
                        "PRAGMA table_info(channel_routing)"
                    ).fetchall()
                }
                if not {"channel_id", "target_account_id"} <= route_columns:
                    raise HTTPException(
                        status_code=503,
                        detail="watcher channel routing schema is unavailable",
                    )
                fields.extend(
                    [
                        "route.target_account_id AS target_account_id",
                        "(SELECT COUNT(*) FROM account_configs AS candidate "
                        "WHERE candidate.execution_account_id = "
                        "account.execution_account_id) "
                        "AS execution_account_count",
                    ]
                )
                rows = conn.execute(
                    "SELECT "
                    + ", ".join(fields)
                    + " FROM channel_routing AS route "
                    + "LEFT JOIN account_configs AS account "
                    + "ON account.account_id = route.target_account_id "
                    + "WHERE route.channel_id = ?",
                    (normalized_channel_id,),
                ).fetchall()
            else:
                rows = conn.execute(
                    "SELECT "
                    + ", ".join(fields)
                    + " FROM account_configs AS account "
                    + "WHERE account.execution_account_id = ?",
                    (normalized_account_id,),
                ).fetchall()
        finally:
            conn.close()
    except HTTPException:
        raise
    except (OSError, sqlite3.Error) as exc:
        raise HTTPException(
            status_code=503,
            detail="watcher account risk configuration is unavailable",
        ) from exc

    if len(rows) != 1:
        raise HTTPException(
            status_code=503,
            detail=(
                f"execution account {normalized_account_id} must resolve "
                "to exactly one risk configuration"
            ),
        )
    row = rows[0]
    credential_account_id = str(row["account_id"] or "").strip()
    execution_account_id = str(
        row["execution_account_id"] or ""
    ).strip()
    if not credential_account_id:
        raise HTTPException(
            status_code=503,
            detail="watcher credential account identity is invalid",
        )
    if execution_account_id != normalized_account_id:
        raise HTTPException(
            status_code=409,
            detail="watcher channel route conflicts with requested account_id",
        )
    if normalized_channel_id:
        target_account_id = str(row["target_account_id"] or "").strip()
        if target_account_id != credential_account_id:
            raise HTTPException(
                status_code=503,
                detail="watcher channel route target account is invalid",
            )
        try:
            execution_account_count = int(row["execution_account_count"])
        except (TypeError, ValueError) as exc:
            raise HTTPException(
                status_code=503,
                detail="watcher execution account identity is invalid",
            ) from exc
        if execution_account_count != 1:
            raise HTTPException(
                status_code=503,
                detail="watcher execution account identity must be unique",
            )
    if not _watcher_account_is_enabled(row, account_columns):
        raise HTTPException(
            status_code=503,
            detail="watcher account risk configuration is disabled",
        )
    try:
        multiplier = float(row["risk_capital_multiplier"])
    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=503,
            detail="watcher account risk capital multiplier is invalid",
        ) from exc
    if not math.isfinite(multiplier) or multiplier <= 0:
        raise HTTPException(
            status_code=503,
            detail="watcher account risk capital multiplier is invalid",
        )
    return multiplier


def _channel_risk_capital_multiplier(
    channel_id: str,
    account_id: str,
) -> float:
    normalized_channel_id = str(channel_id or "").strip()
    if not normalized_channel_id:
        raise HTTPException(
            status_code=503,
            detail="channel risk route has no channel_id",
        )
    return _watcher_risk_capital_multiplier(
        account_id,
        normalized_channel_id,
    )


def _account_risk_capital_multiplier(account_id: str) -> float:
    return _watcher_risk_capital_multiplier(account_id)


def _channel_from_signal_ref(value) -> str | bool:
"""

_FINANCIAL_STATE_REPLACEMENT = """\
def _account_financial_state(account_id: str) -> dict[str, float] | bool:
    \"\"\"Return a fresh Binance USD-M recorder financial snapshot.\"\"\"
    max_age_seconds = 60.0

    database_url = os.environ.get("DATABASE_URL", "").strip()
    if not database_url:
        return False
    try:
        conn = psycopg2.connect(database_url)
        try:
            with conn.cursor() as cur:
                cur.execute(
                    "SELECT equity, available_balance, "
                    "EXTRACT(EPOCH FROM (now() - updated_at)), "
                    "payload->>'account_snapshot_source', "
                    "EXTRACT(EPOCH FROM (now() - "
                    "(payload->>'account_snapshot_fetched_at')::timestamptz)) "
                    "FROM accounts_projection WHERE account_id=%s "
                    "ORDER BY updated_at DESC LIMIT 1",
                    (account_id,),
                )
                row = cur.fetchone()
        finally:
            conn.close()
    except Exception:
        return False
    if not row or row[1] is None:
        return False
    if row[3] != "binance_fapi_account_v3":
        return False
    try:
        equity = float(row[0])
        available_balance = float(row[1])
        projection_age_seconds = float(row[2])
        snapshot_age_seconds = float(row[4])
    except (TypeError, ValueError):
        return False
    values = (
        equity,
        available_balance,
        projection_age_seconds,
        snapshot_age_seconds,
    )
    if not all(math.isfinite(value) for value in values):
        return False
    if equity <= 0 or available_balance < 0:
        return False
    ages = (projection_age_seconds, snapshot_age_seconds)
    if any(age < 0 or age > max_age_seconds for age in ages):
        return False
    return {
        "real_equity": equity,
        "available_balance": available_balance,
    }


def _account_equity(account_id: str) -> float | None:
    state = _account_financial_state(account_id)
    if not state:
        return None
    return state["real_equity"]


"""

_SIZE_OPEN_ORDER_REPLACEMENT = """\
def _size_open_order(explicit_notional, symbol, account_id, side, entry_type,
                     entry_price, entry_price_min, entry_price_max,
                     stop_loss, leverage, caps, checks,
                     risk_capital_multiplier=False) -> float:
    \"\"\"Size from live real equity times the configured account multiplier.\"\"\"
    state = _account_financial_state(account_id)
    if not state:
        raise HTTPException(
            status_code=503,
            detail=f"fresh account financial state unavailable for {account_id}",
        )
    real_equity = state["real_equity"]
    available_balance = state["available_balance"]
    try:
        multiplier = float(risk_capital_multiplier)
    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=503,
            detail="account risk capital multiplier is unavailable",
        ) from exc
    if not math.isfinite(multiplier) or multiplier <= 0:
        raise HTTPException(
            status_code=503,
            detail="account risk capital multiplier is invalid",
        )
    effective_equity = real_equity * multiplier
    checks.append(
        {
            "name": "account_equity_basis",
            "passed": True,
            "real_equity": real_equity,
            "available_balance": available_balance,
            "effective_equity": effective_equity,
            "risk_capital_multiplier": multiplier,
        }
    )
    if entry_type == "limit":
        ref = entry_price
    elif entry_type == "zone":
        if stop_loss is not None:
            ref = (
                entry_price_min
                if abs(entry_price_min - stop_loss)
                >= abs(entry_price_max - stop_loss)
                else entry_price_max
            )
        else:
            ref = (entry_price_min + entry_price_max) / 2
    else:
        ref = _binance_mark_price(symbol)

    try:
        sizing_price = float(ref)
    except (TypeError, ValueError) as exc:
        raise HTTPException(
            status_code=503,
            detail=f"sizing price unavailable for {symbol}",
        ) from exc
    if not math.isfinite(sizing_price) or sizing_price <= 0:
        raise HTTPException(
            status_code=503,
            detail=f"sizing price unavailable for {symbol}",
        )
    ref = sizing_price

    notional: float
    if stop_loss is not None:
        if side == "short" and stop_loss <= ref:
            raise HTTPException(
                status_code=400,
                detail="short stop_loss must be above entry",
            )
        if side == "long" and stop_loss >= ref:
            raise HTTPException(
                status_code=400,
                detail="long stop_loss must be below entry",
            )
        stop_frac = abs(ref - stop_loss) / ref
        risk_ratio = _symbol_risk_ratio(symbol)
        auto = effective_equity * risk_ratio / stop_frac
        allow_canary_override = (
            caps.get("_canary_explicit_notional_override") is True
        )
        if (
            explicit_notional is not None
            and explicit_notional > auto + 1e-9
            and not allow_canary_override
        ):
            raise HTTPException(
                status_code=400,
                detail=(
                    f"explicit notional {explicit_notional:.1f}U exceeds "
                    f"dynamic auto sizing {auto:.1f}U"
                ),
            )
        notional = explicit_notional if explicit_notional is not None else auto
        max_risk = effective_equity * caps["max_risk_fraction"]
        est_risk = notional * stop_frac
        if est_risk > max_risk + 1e-9:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"loss at stop ~{est_risk:.1f}U exceeds per-order risk cap "
                    f"{max_risk:.1f}U ({caps['max_risk_fraction']:.0%} of "
                    f"effective equity {effective_equity:.0f}U)"
                ),
            )
        checks.append(
            {
                "name": "risk_sizing",
                "passed": True,
                "real_equity": real_equity,
                "effective_equity": effective_equity,
                "risk_ratio": risk_ratio,
                "stop_frac": round(stop_frac, 5),
                "sizing_price": ref,
                "notional": round(notional, 1),
                "est_risk": round(est_risk, 1),
                "risk_cap": round(max_risk, 1),
                "auto_sized": explicit_notional is None,
            }
        )
    else:
        if explicit_notional is None:
            raise HTTPException(
                status_code=400,
                detail=(
                    "auto-sizing needs a stop_loss (and a resolvable price); "
                    "pass notional_usdt explicitly for stop-less orders"
                ),
            )
        ceiling = effective_equity * caps["no_sl_equity_fraction"]
        if explicit_notional > ceiling:
            raise HTTPException(
                status_code=400,
                detail=(
                    f"stop-less order notional {explicit_notional:.0f}U exceeds "
                    f"{ceiling:.0f}U "
                    f"({caps['no_sl_equity_fraction']:.0%} of equity)"
                ),
            )
        notional = explicit_notional
        checks.append(
            {
                "name": "no_sl_notional_cap",
                "passed": True,
                "notional": notional,
                "ceiling": round(ceiling, 1),
            }
        )

    hard_leverage = leverage or caps["max_leverage"]
    real_equity_ceiling = real_equity * hard_leverage
    if notional > real_equity_ceiling:
        raise HTTPException(
            status_code=400,
            detail=(
                f"notional {notional:.0f}U exceeds real_equity*leverage "
                f"{real_equity_ceiling:.0f}U"
            ),
        )
    available_ceiling = available_balance * hard_leverage
    if notional > available_ceiling:
        raise HTTPException(
            status_code=400,
            detail=(
                f"notional {notional:.0f}U exceeds available_balance*leverage "
                f"{available_ceiling:.0f}U"
            ),
        )
    checks.append(
        {
            "name": "real_funds_gate",
            "passed": True,
            "leverage": hard_leverage,
            "real_equity_ceiling": round(real_equity_ceiling, 1),
            "available_balance_ceiling": round(available_ceiling, 1),
        }
    )
    if caps["max_notional"] and notional > caps["max_notional"]:
        raise HTTPException(
            status_code=400,
            detail=(
                f"notional {notional:.0f}U exceeds "
                "OPERATOR_MAX_NOTIONAL_USDT "
                f"{caps['max_notional']:.0f}U"
            ),
        )
    return notional


"""

_OPEN_ROUTE_ANCHOR = """\
    client_ref = str(body.get("client_ref") or "").strip()
    explicit_intent_id = _explicit_operator_intent_id(body)
"""

_OPEN_ROUTE_REPLACEMENT = """\
    client_ref = str(body.get("client_ref") or "").strip()
    explicit_intent_id = _explicit_operator_intent_id(body)
    open_raw_channel = "hermes-operator"
    open_has_provenance = False
    open_risk_capital_multiplier: float | bool = False
    if action == "open_position":
        open_raw_channel, open_has_provenance = _open_source_channel(
            body,
            client_ref,
        )
        if open_raw_channel not in ("hermes-operator", "operator"):
            open_risk_capital_multiplier = (
                _channel_risk_capital_multiplier(
                    open_raw_channel,
                    account_id,
                )
            )
        else:
            open_risk_capital_multiplier = (
                _account_risk_capital_multiplier(account_id)
            )
"""

_LEVERAGE_VALIDATION_ANCHOR = """\
    leverage = _op_num(body.get("leverage"), "leverage")
    if leverage is not None and leverage > caps["max_leverage"]:
"""

_LEVERAGE_VALIDATION_REPLACEMENT = """\
    leverage = _op_num(body.get("leverage"), "leverage")
    if leverage is not None and leverage <= 0:
        raise HTTPException(
            status_code=400,
            detail="leverage must be greater than zero",
        )
    if leverage is not None and leverage > caps["max_leverage"]:
"""

_SIZE_CALL_ANCHOR = """\
            entry_price, entry_price_min, entry_price_max,
            stop_loss, caps, checks,
        )
"""

_SIZE_CALL_REPLACEMENT = """\
            entry_price, entry_price_min, entry_price_max,
            stop_loss, leverage, caps, checks,
            open_risk_capital_multiplier,
        )
"""

_RAW_CHANNEL_ANCHOR = """\
    raw_channel = "hermes-operator"
    has_provenance = False
    if action == "open_position":
        raw_channel, has_provenance = _open_source_channel(body, client_ref)
"""

_RAW_CHANNEL_REPLACEMENT = """\
    raw_channel = open_raw_channel
    has_provenance = open_has_provenance
"""


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _replace_exact(
    source: str,
    old: str,
    new: str,
    label: str,
) -> str:
    count = source.count(old)
    if count != 1:
        raise PatchError(
            f"{label} anchor count must be 1, found {count}"
        )
    return source.replace(old, new, 1)


def _replace_region(
    source: str,
    start: str,
    end: str,
    replacement: str,
    label: str,
) -> str:
    start_count = source.count(start)
    end_count = source.count(end)
    if start_count != 1 or end_count != 1:
        raise PatchError(
            f"{label} anchors must each occur once; "
            f"found start={start_count}, end={end_count}"
        )
    start_index = source.index(start)
    end_index = source.index(end, start_index)
    if end_index <= start_index:
        raise PatchError(f"{label} anchors are out of order")
    return source[:start_index] + replacement + source[end_index:]


def _validate_patched_source(source: str) -> None:
    required = (
        PATCH_MARKER,
        '"account-c"',
        '"account-d"',
        "def _channel_risk_capital_multiplier(",
        "def _account_risk_capital_multiplier(",
        "WHERE account.execution_account_id = ?",
        "effective_equity = real_equity * multiplier",
        "payload->>'account_snapshot_source'",
        '"binance_fapi_account_v3"',
        "payload->>'account_snapshot_fetched_at'",
        "max_age_seconds = 60.0",
        "explicit_notional > auto + 1e-9",
        "sizing_price = float(ref)",
        "if not math.isfinite(sizing_price) or sizing_price <= 0:",
        "real_equity_ceiling = real_equity * hard_leverage",
        "available_ceiling = available_balance * hard_leverage",
        "open_risk_capital_multiplier,",
        "raw_channel = open_raw_channel",
    )
    for snippet in required:
        if source.count(snippet) != 1:
            raise PatchError(
                f"patched source invariant failed for {snippet!r}"
            )
    if _OLD_ACCOUNTS in source:
        raise PatchError("legacy two-account allowlist remains after patch")
    forbidden = (
        "OPERATOR_EQUITY_",
        "OPERATOR_AVAILABLE_BALANCE_",
        "max(equity - margin",
        "9000",
    )
    for snippet in forbidden:
        if snippet in source:
            raise PatchError(
                f"patched source contains forbidden runtime value {snippet!r}"
            )
    try:
        compile(source, "read_api.py", "exec")
    except SyntaxError as exc:
        raise PatchError("patched source does not compile") from exc


def patch_source(source: str) -> str:
    source_sha256 = _sha256(source.encode("utf-8"))
    if source_sha256 != EXPECTED_SOURCE_SHA256:
        raise PatchError(
            "input SHA256 mismatch: "
            f"expected {EXPECTED_SOURCE_SHA256}, got {source_sha256}"
        )
    if PATCH_MARKER in source:
        raise PatchError("input contains a partial or unreviewed patch marker")

    patched = _replace_exact(
        source,
        _OLD_ACCOUNTS,
        _NEW_ACCOUNTS,
        "operator accounts",
    )
    patched = _replace_exact(
        patched,
        _ROUTING_INSERT_ANCHOR,
        _ROUTING_INSERT_REPLACEMENT,
        "watcher routing insertion",
    )
    patched = _replace_region(
        patched,
        "def _account_equity(account_id: str) -> float | None:\n",
        "def _symbol_risk_ratio(symbol: str) -> float:\n",
        _FINANCIAL_STATE_REPLACEMENT,
        "account financial state",
    )
    patched = _replace_region(
        patched,
        "def _size_open_order(explicit_notional, symbol, account_id, side, entry_type,\n",
        "def _validate_stop_direction(symbol: str, account_id: str, stop_loss: float,\n",
        _SIZE_OPEN_ORDER_REPLACEMENT,
        "open order sizing",
    )
    patched = _replace_exact(
        patched,
        _OPEN_ROUTE_ANCHOR,
        _OPEN_ROUTE_REPLACEMENT,
        "open route resolution",
    )
    patched = _replace_exact(
        patched,
        _LEVERAGE_VALIDATION_ANCHOR,
        _LEVERAGE_VALIDATION_REPLACEMENT,
        "leverage validation",
    )
    patched = _replace_exact(
        patched,
        _SIZE_CALL_ANCHOR,
        _SIZE_CALL_REPLACEMENT,
        "open sizing call",
    )
    patched = _replace_exact(
        patched,
        _RAW_CHANNEL_ANCHOR,
        _RAW_CHANNEL_REPLACEMENT,
        "raw channel reuse",
    )
    _validate_patched_source(patched)
    return patched


def _backup_path(target: Path, backup_dir: Path | None) -> Path:
    directory = backup_dir
    if directory is None:
        directory = target.parent
    name = (
        f"{target.name}.pre-multiplier."
        f"{EXPECTED_SOURCE_SHA256[:16]}.bak"
    )
    return directory / name


def _fsync_directory(directory: Path) -> None:
    flags = os.O_RDONLY
    if hasattr(os, "O_DIRECTORY"):
        flags |= os.O_DIRECTORY
    fd = os.open(directory, flags)
    try:
        os.fsync(fd)
    except OSError as exc:
        if exc.errno not in {errno.EINVAL, errno.ENOTSUP}:
            raise
    finally:
        os.close(fd)


def _write_temp(
    directory: Path,
    prefix: str,
    data: bytes,
    mode: int,
    uid: int,
    gid: int,
) -> Path:
    fd, raw_path = tempfile.mkstemp(prefix=prefix, dir=directory)
    path = Path(raw_path)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(data)
            handle.flush()
            os.fsync(handle.fileno())
            os.fchmod(handle.fileno(), mode)
            os.fchown(handle.fileno(), uid, gid)
    except Exception:
        path.unlink(missing_ok=True)
        raise
    return path


def _ensure_backup(
    backup: Path,
    source: bytes,
    mode: int,
    uid: int,
    gid: int,
) -> None:
    backup.parent.mkdir(parents=True, exist_ok=True)
    if backup.is_symlink():
        raise PatchError(f"backup must not be a symlink: {backup}")
    if backup.exists():
        backup_stat = backup.stat()
        if not stat.S_ISREG(backup_stat.st_mode):
            raise PatchError(f"backup must be a regular file: {backup}")
        existing = backup.read_bytes()
        if _sha256(existing) != EXPECTED_SOURCE_SHA256:
            raise PatchError(
                f"backup exists with unexpected content: {backup}"
            )
        return
    temporary = _write_temp(
        backup.parent,
        f".{backup.name}.",
        source,
        mode,
        uid,
        gid,
    )
    try:
        try:
            os.link(temporary, backup)
        except FileExistsError:
            existing = backup.read_bytes()
            if _sha256(existing) != EXPECTED_SOURCE_SHA256:
                raise PatchError(
                    f"backup race produced unexpected content: {backup}"
                )
        _fsync_directory(backup.parent)
    finally:
        temporary.unlink(missing_ok=True)


def _atomic_replace(
    target: Path,
    data: bytes,
    mode: int,
    uid: int,
    gid: int,
) -> None:
    temporary = _write_temp(
        target.parent,
        f".{target.name}.multiplier.",
        data,
        mode,
        uid,
        gid,
    )
    try:
        os.replace(temporary, target)
        _fsync_directory(target.parent)
    finally:
        temporary.unlink(missing_ok=True)


def patch_file(
    target: Path,
    backup_dir: Path | None = None,
    check_only: bool = False,
) -> dict[str, str]:
    target = target.expanduser().absolute()
    if target.is_symlink():
        raise PatchError(f"target must not be a symlink: {target}")
    try:
        target_stat = target.stat()
        source = target.read_bytes()
    except OSError as exc:
        raise PatchError(f"cannot read target: {target}") from exc
    if not stat.S_ISREG(target_stat.st_mode):
        raise PatchError(f"target must be a regular file: {target}")

    source_sha256 = _sha256(source)
    backup = _backup_path(target, backup_dir)
    if source_sha256 == EXPECTED_PATCHED_SHA256:
        try:
            patched_text = source.decode("utf-8")
        except UnicodeDecodeError as exc:
            raise PatchError("patched target is not UTF-8") from exc
        _validate_patched_source(patched_text)
        if backup.is_symlink() or not backup.is_file():
            raise PatchError(
                f"patched target has no reviewed backup: {backup}"
            )
        if _sha256(backup.read_bytes()) != EXPECTED_SOURCE_SHA256:
            raise PatchError(
                f"patched target backup has unexpected content: {backup}"
            )
        return {
            "status": "already_patched",
            "target": str(target),
            "source_sha256": source_sha256,
            "patched_sha256": EXPECTED_PATCHED_SHA256,
            "backup": str(backup),
        }
    if PATCH_MARKER.encode("utf-8") in source:
        raise PatchError("target contains a partial or unreviewed patch marker")
    if source_sha256 != EXPECTED_SOURCE_SHA256:
        raise PatchError(
            "target SHA256 mismatch: "
            f"expected {EXPECTED_SOURCE_SHA256}, got {source_sha256}"
        )
    try:
        source_text = source.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise PatchError("target is not UTF-8") from exc
    patched_text = patch_source(source_text)
    patched = patched_text.encode("utf-8")
    patched_sha256 = _sha256(patched)
    if patched_sha256 != EXPECTED_PATCHED_SHA256:
        raise PatchError(
            "generated patch SHA256 mismatch: "
            f"expected {EXPECTED_PATCHED_SHA256}, got {patched_sha256}"
        )
    result_status = "ready"
    if check_only:
        return {
            "status": result_status,
            "target": str(target),
            "source_sha256": source_sha256,
            "patched_sha256": patched_sha256,
            "backup": str(backup),
        }

    current_sha256 = _sha256(target.read_bytes())
    if current_sha256 != EXPECTED_SOURCE_SHA256:
        raise PatchError(
            "target changed after validation: "
            f"expected {EXPECTED_SOURCE_SHA256}, got {current_sha256}"
        )
    mode = stat.S_IMODE(target_stat.st_mode)
    _ensure_backup(
        backup,
        source,
        mode,
        target_stat.st_uid,
        target_stat.st_gid,
    )
    current_sha256 = _sha256(target.read_bytes())
    if current_sha256 != EXPECTED_SOURCE_SHA256:
        raise PatchError(
            "target changed while backup was created: "
            f"expected {EXPECTED_SOURCE_SHA256}, got {current_sha256}"
        )
    _atomic_replace(
        target,
        patched,
        mode,
        target_stat.st_uid,
        target_stat.st_gid,
    )
    final_sha256 = _sha256(target.read_bytes())
    if final_sha256 != EXPECTED_PATCHED_SHA256:
        raise PatchError(
            "atomic replacement verification failed: "
            f"expected {EXPECTED_PATCHED_SHA256}, got {final_sha256}"
        )
    return {
        "status": "patched",
        "target": str(target),
        "source_sha256": source_sha256,
        "patched_sha256": final_sha256,
        "backup": str(backup),
    }


def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Patch the pinned HK legacy control-plane with dynamic "
            "watcher account multipliers."
        )
    )
    parser.add_argument(
        "target",
        nargs="?",
        type=Path,
        default=DEFAULT_TARGET,
    )
    parser.add_argument("--backup-dir", type=Path)
    parser.add_argument("--check", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = _parse_args(argv)
    try:
        result = patch_file(
            args.target,
            backup_dir=args.backup_dir,
            check_only=args.check,
        )
    except PatchError as exc:
        print(
            json.dumps(
                {
                    "status": "rejected",
                    "error": str(exc),
                },
                sort_keys=True,
            )
        )
        return 2
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
