#!/usr/bin/env bash
set -euo pipefail

REMOTE_HOST="${REMOTE_HOST:-root@149.104.30.223}"
REMOTE_DIR="${REMOTE_DIR:-/root/freqtrade}"
SIGNAL_STORE_URL="${SIGNAL_STORE_URL:-sqlite:///$REMOTE_DIR/user_data/signal_strategy.sqlite3}"
SIGNAL_PAIR_WHITELIST="${SIGNAL_PAIR_WHITELIST:-BTC/USDT:USDT,ETH/USDT:USDT,SOL/USDT:USDT,LA/USDT:USDT,TAO/USDT:USDT,ZKP/USDT:USDT,LTC/USDT:USDT}"
WATCHER_HOST="${WATCHER_HOST:-127.0.0.1}"

export NODE_ENV=production
export HERMES_PROFILE=trader
export HERMES_ACCEPT_HOOKS=1
export WATCHER_HOST
export HERMES_SIGNAL_STORE_URL="$SIGNAL_STORE_URL"
export SIGNAL_IMPORTER_PYTHON=python3
export SIGNAL_IMPORTER_MODULE="${SIGNAL_IMPORTER_MODULE:-}"
export SIGNAL_IMPORTER_CWD=
export SIGNAL_IMPORTER_REMOTE_HOST="$REMOTE_HOST"
export SIGNAL_IMPORTER_REMOTE_CWD="$REMOTE_DIR"
export SIGNAL_IMPORTER_SSH_IPV6="${SIGNAL_IMPORTER_SSH_IPV6:-0}"
export SIGNAL_PAIR_WHITELIST
export SIGNAL_IMPORTER_ENABLED=0
export SIGNAL_IMPORTER_MAX_IN_FLIGHT=1
export HERMES_TRADER_CRON_ENABLED=0

pm2 startOrReload ecosystem.config.js --update-env
pm2 save
